/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.FileNotFoundException;
import java.io.FileReader;

public class App {
    public static void main(String[] args) throws FileNotFoundException {

//        RandomQuotes randquote = new RandomQuotes("This random quote", "Andy Shoemaker");
//        System.out.println(randquote);

        Gson gson = new Gson();

        RandomQuotes[] parseSourceQuotes = gson.fromJson(new FileReader("resources/recentquotes.json"), RandomQuotes[].class);
//        System.out.println(gson.toJson(parseSourceQuotes));
//        System.out.println(parseSourceQuotes);
//        System.out.println(parseSourceQuotes[randomizer()].author + parseSourceQuotes[randomizer()].author);

        int index = randomizer();
        RandomQuotes randquote = new RandomQuotes(parseSourceQuotes[index].author, parseSourceQuotes[index].likes ,parseSourceQuotes[index].text);
        System.out.println(randquote);


    }


    public static int randomizer(){
        int x = (int)(Math.random() * 138);
        return x;
    }

}
